import {useEffect, useState} from 'react';
import {CircleCheck, Download, FileVideo, FolderOpen, LoaderCircle, Pause, Play, Subtitles, X} from 'lucide-react';
import {api, busy, lang, parentFolder} from './api';
import type {Job, Project} from './types';
import {FilePicker} from './file-picker';

type Actions = {onJob:(job:Job)=>void;fail:(error:unknown)=>void};
type Choice = {track:number;language:string;label:string;kind:string;native:boolean};
const choiceKey = (choice:Choice) => `${choice.track}/${choice.language}`;

export function MediaJobStatus({job,onJob,fail,retry}:Actions & {job?:Job;retry?:()=>void}) {
  if (!job) return null;
  return <div className="media-job" role="status"><div className="section-heading"><strong>{job.status==='done'?'Subtitled video saved':job.message}</strong><span>{Math.round(job.progress*100)}%</span></div>
    <div className="progress-track"><div style={{width:`${job.progress*100}%`}}/></div>
    {job.error && <div className="alert error" role="alert">{job.error}</div>}{job.warnings.map(w=><p className="media-warning" key={w}>{w}</p>)}
    {busy(job)?<button className="button quiet small" onClick={()=>api<Job>(`/jobs/${job.id}/pause`,'POST',{}).then(onJob).catch(fail)}><Pause size={14}/>Pause</button>:['paused','failed','cancelled'].includes(job.status)?<button className="button secondary small" onClick={()=>retry?retry():api<Job>(`/jobs/${job.id}/resume`,'POST',{}).then(onJob).catch(fail)}><Play size={14}/>Retry saving</button>:null}
    {job.status==='done' && job.result?.path && <><p className="saved-path">{job.result.path}</p><button className="button secondary" onClick={()=>api(`/jobs/${job.id}/play-output`,'POST',{}).catch(fail)}><Play size={15}/>Play saved video in VLC</button></>}
  </div>;
}

export function EmbeddedPanel({project,languages,job,onJob,fail,onReview,onEmbed}:Actions & {project:Project;languages:string[];job?:Job;onReview:(track:number)=>void;onEmbed:()=>void}) {
  const tracks = project.media.subtitle_tracks||[];
  const [sources,setSources] = useState<Record<number,string>>({});
  useEffect(()=>setSources(Object.fromEntries(tracks.map(t=>[t.cue_track,t.language==='und'?'':t.language]))),[project.id,JSON.stringify(tracks)]);
  if (!tracks.length) return null;
  async function importing(track:number) {
    const value = await api<Job>(`/projects/${project.id}/subtitles/import`,'POST',{tracks:[track],languages:{[track]:sources[track]}});
    onJob(value);
  }
  return <section className="panel embedded-panel"><div className="section-heading"><div><h3><Subtitles size={18}/>Subtitles already in this video</h3><p>Use an existing text track directly, or extract its original format.</p></div><span className="pill">{tracks.length} {tracks.length===1?'track':'tracks'}</span></div>
    {tracks.map(t=>{const imported=project.cue_counts.find(c=>c.track===t.cue_track);const extracted=job?.result?.subtitles?.some(s=>s.track===t.cue_track);const changed=sources[t.cue_track]!==t.language;return <div className="embedded-track" key={t.cue_track}>
      <div className="embedded-description"><strong>{t.title||`Subtitle track ${t.subtitle_ordinal+1}`}</strong><small>{lang(t.language)} · {t.codec.toUpperCase()}{t.default?' · Default':''}{t.forced?' · Forced':''}</small><span className={`pill ${t.kind==='image'?'image-pill':''}`}>{t.kind==='text'?'Editable text':t.kind==='image'?'Image subtitles':'Original format'}</span></div>
      {t.kind==='text' && <label className="embedded-language">Text language<select aria-label={`Subtitle ${t.subtitle_ordinal+1} source language`} value={sources[t.cue_track]||''} onChange={e=>setSources({...sources,[t.cue_track]:e.target.value})}><option value="">Choose language…</option>{languages.map(code=><option value={code} key={code}>{lang(code)}</option>)}</select></label>}
      <div className="embedded-actions">{t.kind==='text' && (imported&&!changed?<button className="button primary small" onClick={()=>onReview(t.cue_track)}><Subtitles size={14}/>Review & translate</button>:<button className="button primary small" disabled={busy(job)||!sources[t.cue_track]} onClick={()=>importing(t.cue_track).catch(fail)}>{imported?'Update & review':'Import & review'}</button>)}<button className="button secondary small" disabled={busy(job)} onClick={()=>api<Job>(`/projects/${project.id}/subtitles/extract`,'POST',{tracks:[t.cue_track]}).then(onJob).catch(fail)}><Download size={14}/>Extract original</button>{extracted && <a className="button quiet small" href={`/api/projects/${project.id}/subtitles/file?track=${t.cue_track}&k=${encodeURIComponent(window.STUDIO_TOKEN)}`} download>Download {t.extract_extension.toUpperCase()}</a>}</div>
      {t.kind==='image' && <p className="embedded-limit">These subtitles are pictures. You can extract or preserve them in MKV. Translation requires OCR; alternatively, create text subtitles from the audio.</p>}
    </div>;})}
    {job && ['import_subtitles','extract_subtitles'].includes(job.kind) && <div className="inline-progress">{busy(job)?<LoaderCircle className="spin" size={16}/>:<CircleCheck size={16}/>}<span>{job.status==='done'?'Subtitle track ready':job.message}</span><span>{Math.round(job.progress*100)}%</span>{job.error && <div className="alert error">{job.error}</div>}{['failed','paused','cancelled'].includes(job.status)&&<button className="button secondary small" onClick={()=>api<Job>(`/jobs/${job.id}/resume`,'POST',{}).then(onJob).catch(fail)}>Retry</button>}</div>}
    <div className="embedded-footer"><p>Original styled tracks stay available when you save a new video.</p><button className="button secondary" disabled={busy(job)} onClick={onEmbed}><FileVideo size={16}/>Save a subtitled video</button></div>
  </section>;
}

export function RemuxModal({project,initial,job,onJob,close,fail}:Actions & {project:Project;initial?:{track:number;language:string};job?:Job;close:()=>void}) {
  const [options,setOptions]=useState<Choice[]>([]),[selected,setSelected]=useState<string[]>([]),[defaultKey,setDefaultKey]=useState(''),[output,setOutput]=useState(''),[keep,setKeep]=useState(true),[ownJob,setOwnJob]=useState(''),[error,setError]=useState(''),[starting,setStarting]=useState(false);
  const [choosingFolder,setChoosingFolder]=useState(false);
  const active = job?.id===ownJob ? job : undefined;
  useEffect(()=>{api<{subtitles:Choice[];suggested_output:string}>(`/projects/${project.id}/subtitles/options`).then(value=>{setOptions(value.subtitles);setOutput(value.suggested_output);const choice=value.subtitles.find(c=>c.track===initial?.track&&c.language===initial.language)||value.subtitles[0];if(choice){const key=choiceKey(choice);setSelected([key]);setDefaultKey(key);}}).catch(e=>setError(e.message));},[project.id]);
  function folder() {setChoosingFolder(true);}
  async function saving() {setError('');setStarting(true);try {const value=await api<Job>(`/projects/${project.id}/subtitles/embed`,'POST',{output_path:output,keep_embedded:keep,subtitles:options.filter(c=>selected.includes(choiceKey(c))).map(c=>({track:c.track,language:c.language,default:choiceKey(c)===defaultKey}))});setOwnJob(value.id);onJob(value);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setStarting(false);}}
  const mp4=/\.mp4$/i.test(output);
  if(active?.status==='done' && active.result?.path) return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className="settings-modal remux-modal" role="dialog" aria-modal="true" aria-labelledby="remux-done-title"><div className="modal-heading"><div><div className="eyebrow">READY TO WATCH</div><h2 id="remux-done-title">Your video is ready.</h2></div><button className="icon-button" aria-label="Close video export" onClick={close}><X/></button></div><div className="mux-success"><CircleCheck size={42}/><p>{active.result.subtitle_count} subtitle tracks, ready to choose in your player.<br/>Video and audio retain their original quality.</p></div><div className="mux-selected-result">{options.filter(c=>selected.includes(choiceKey(c))).map(c=><div key={choiceKey(c)}><Subtitles size={17}/><span>{c.language==='original'?c.label:`${lang(c.language)} · ${c.label}`}{choiceKey(c)===defaultKey&&<small>Default subtitle track</small>}</span></div>)}</div><MediaJobStatus job={active} onJob={onJob} fail={fail}/><button className="button primary full" onClick={close}>Done</button></section></div>;
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className="settings-modal remux-modal" role="dialog" aria-modal="true" aria-labelledby="remux-title"><div className="modal-heading"><div><div className="eyebrow">READY TO WATCH</div><h2 id="remux-title">Save a subtitled video</h2></div><button className="icon-button" aria-label="Close video export" onClick={close}><X/></button></div><p>Pick the subtitle versions to include. Video and audio are copied at their original quality into a new file.</p>
    {error&&<div className="alert error" role="alert">{error}</div>}
    <div className="mux-choices">{options.map(c=>{const key=choiceKey(c);return <div className={`mux-choice ${selected.includes(key)?'selected':''}`} key={key}><label><input type="checkbox" aria-label={`Include ${c.label} ${c.language}`} disabled={busy(active)} checked={selected.includes(key)} onChange={e=>{setSelected(e.target.checked?[...selected,key]:selected.filter(k=>k!==key));if(!e.target.checked&&defaultKey===key)setDefaultKey('');}}/><span><strong>{c.language==='original'?c.label:`${lang(c.language)} · ${c.label}`}</strong><small>{c.native?'Original embedded track':c.language==='original'?'Reviewed subtitle text':'Completed translation'}{c.kind==='image'?' · image subtitles':''}</small></span></label><label className="mux-default"><input type="radio" name="default-subtitle" aria-label={`Default ${c.label} ${c.language}`} disabled={!selected.includes(key)||busy(active)} checked={defaultKey===key} onChange={()=>setDefaultKey(key)}/>Default</label></div>;})}{!options.length && <p>No subtitle versions are available yet.</p>}</div>
    <label className="toggle"><input type="checkbox" checked={keep} disabled={busy(active)} onChange={e=>setKeep(e.target.checked)}/><div><strong>Keep the other embedded subtitles</strong><small>Unselected original tracks remain available in the saved video.</small></div></label>
    <label className="field">Video format<select aria-label="Video output format" disabled={busy(active)} value={mp4?'mp4':'mkv'} onChange={e=>setOutput(output.replace(/\.[^.\\/]+$/,'')+'.'+e.target.value)}><option value="mkv">MKV · best format support</option><option value="mp4">MP4 · text subtitles</option></select></label><p className="media-warning">{mp4?'MP4 uses timed text. Image tracks and font attachments need MKV; advanced subtitle styling is converted.':'MKV preserves original styled/image tracks and attachments. Translated or edited tracks use simple SRT styling.'}</p>
    <label className="field">New video file<div className="output-path-row"><input aria-label="New subtitled video path" value={output} disabled={busy(active)} onChange={e=>setOutput(e.target.value)}/><button className="button secondary" aria-label="Choose video output folder" disabled={busy(active)} onClick={folder}><FolderOpen size={17}/></button></div></label>
    <p className="media-warning">Choose a new filename. Existing files and the source video are never overwritten.</p>
    {active?<MediaJobStatus job={active} onJob={onJob} fail={fail} retry={()=>{if(selected.length&&output&&!starting)saving();}}/>:<button className="button primary full" disabled={!selected.length||!output||starting||busy(job)} onClick={saving}>{starting?<LoaderCircle className="spin" size={17}/>:<FileVideo size={17}/>}Save video</button>}
  </section>{choosingFolder&&<FilePicker kind="folder" initialDirectory={parentFolder(output)} close={()=>setChoosingFolder(false)} onChoose={path=>{setOutput(path.replace(/[\\/]$/,'')+'/' + output.split(/[\\/]/).pop());setChoosingFolder(false);}}/>}</div>;
}
