import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {useVirtualizer} from '@tanstack/react-virtual';
import {AudioLines, ArrowRight, Check, ChevronLeft, CircleCheck, Download, FileVideo, Film, FolderOpen, Globe2, Layers3, LoaderCircle, MessageSquare, Pause, Play, RefreshCw, Settings2, ShieldCheck, Sparkles, Subtitles, TriangleAlert, X} from 'lucide-react';
import './styles.css';

declare global {interface Window {STUDIO_TOKEN: string}}
type Track = {stream_index: number; audio_ordinal: number; channels: number; codec: string; title: string; detection: string; languages: {code: string; score?: number}[]};
type Job = {id: string; kind: string; status: string; stage: string; progress: number; message: string; elapsed: number; error?: string; warnings: string[]};
type Project = {id: string; media: {name: string; path: string; duration: number; size: number; warnings: string[]; audio_tracks: Track[]}; jobs: Job[]; cue_counts: {track: number; count: number}[]};
type Candidate = {id: string; text: string; engine: string};
type Vote = {role: string; round: number; candidate_id: string; reason: string};
type Cue = {id: string; track: number; start: number; end: number; text: string; raw_text: string; language: string; flags: string[]; reviewed: boolean; candidates: Candidate[]; verification?: string; translated_text?: string; decision?: {status: string; selected: string; votes: Vote[]}};
type System = {version: string; gpu?: {name: string; total_mb: number; free_mb: number}; tools: Record<string, string | null>; models: {id: string; name: string; ready: boolean; size_gb: number}[]; models_root: string; ollama_models: string; setup_jobs: Job[]; preferences: Record<string, unknown>};
type Clip = {url: string; start: number; duration: number; peaks: number[]};

async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> {
  const response = await fetch('/api' + path, {method, headers: {'Content-Type': 'application/json', 'X-Studio-Token': window.STUDIO_TOKEN}, body: body === undefined ? undefined : JSON.stringify(body)});
  if (!response.ok) {const value = await response.json().catch(() => ({})); throw new Error(typeof value.detail === 'string' ? value.detail : 'The request could not be completed.');}
  return response.json();
}
const busy = (job?: Job) => !!job && ['queued','running','pausing'].includes(job.status);
const duration = (value: number) => {const sec = Math.max(0, Math.floor(value)); return sec >= 3600 ? `${Math.floor(sec/3600)}:${String(Math.floor(sec/60)%60).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}` : `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;};
const lang = (code: string) => {try {return new Intl.DisplayNames(['en'], {type:'language'}).of(code) || code;} catch {return code;}};
const size = (bytes: number) => bytes > 1e9 ? `${(bytes/1e9).toFixed(1)} GB` : `${Math.round(bytes/1e6)} MB`;

function App() {
  const [system, setSystem] = useState<System>();
  const [projects, setProjects] = useState<Project[]>([]);
  const [library, setLibrary] = useState<{name:string;path:string;size:number}[]>([]);
  const [project, setProject] = useState<Project>();
  const [tracks, setTracks] = useState<number[]>([]);
  const [job, setJob] = useState<Job>();
  const [step, setStep] = useState<'choose'|'process'|'review'>('choose');
  const [modal, setModal] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [opening, setOpening] = useState(false);
  const [path, setPath] = useState('');
  const [preset, setPreset] = useState('accurate');
  const [sourceLanguage, setSourceLanguage] = useState('');
  const [recheck, setRecheck] = useState(true);
  const [debate, setDebate] = useState(true);
  const [sample, setSample] = useState(false);
  const [sampleStart, setSampleStart] = useState(0);
  const [languages, setLanguages] = useState<{transcription:string[];translation:string[]}>({transcription:[],translation:[]});

  const notify = (message: string) => {setNotice(message); window.setTimeout(() => setNotice(''), 6500);};
  const fail = (e: unknown) => setError(e instanceof Error ? e.message : String(e));
  const reloadSystem = async () => setSystem(await api<System>('/system'));
  const refreshProject = async (id: string) => {const p = await api<Project>('/projects/'+id); setProject(p); setProjects(await api<Project[]>('/projects')); return p;};
  useEffect(() => {Promise.all([reloadSystem(), api<Project[]>('/projects').then(setProjects), api<typeof library>('/library').then(setLibrary), api<typeof languages>('/languages').then(setLanguages)]).catch(fail);}, []);
  useEffect(() => {const timer = window.setInterval(() => reloadSystem().catch(()=>{}), 15000); return () => clearInterval(timer);}, []);
  useEffect(() => {
    if (!job || !busy(job)) return;
    const source = new EventSource(`/api/jobs/${job.id}/events?k=${encodeURIComponent(window.STUDIO_TOKEN)}`);
    source.onmessage = event => {const updated = JSON.parse(event.data) as Job; setJob(updated); if (!busy(updated)) {source.close(); if (project) refreshProject(project.id).then(p => {if (updated.kind === 'transcribe' && updated.status === 'done') setStep('review'); if (updated.kind === 'scan') setStep('choose');}).catch(fail); reloadSystem().catch(()=>{});}};
    return () => source.close();
  }, [job?.id, job?.status]);

  async function openVideo(videoPath: string) {
    setError(''); setOpening(true);
    try {const p = await api<Project>('/projects', 'POST', {path: videoPath}); setProject(p); setTracks(p.media.audio_tracks.slice(0,1).map(t=>t.stream_index)); setJob(p.jobs.find(busy) || p.jobs[0]); setStep(p.cue_counts.length ? 'review' : 'choose'); setProjects(await api<Project[]>('/projects'));}
    catch (e) {fail(e);} finally {setOpening(false);}
  }
  async function browse() {try {const value = await api<{path:string|null}>('/browse','POST',{kind:'file'}); if (value.path) await openVideo(value.path);} catch(e) {fail(e);}}
  async function start() {if (!project) return; setError(''); try {const j = await api<Job>(`/projects/${project.id}/jobs`,'POST',{tracks, settings:{preset,language:sourceLanguage||null,recheck,debate,start_seconds:sample ? sampleStart : 0,limit_seconds:sample ? 120 : null}}); setJob(j); setStep('process');} catch(e) {fail(e);}}
  async function selectProject(p: Project) {const current = await refreshProject(p.id); setTracks(current.media.audio_tracks.slice(0,1).map(t=>t.stream_index)); setJob(current.jobs.find(busy) || current.jobs[0]); setStep(current.cue_counts.length ? 'review' : 'choose');}
  const selectedTrack = project?.media.audio_tracks.find(t=>tracks.includes(t.stream_index));
  const ready = system?.models.filter(m=>['whisper','qwen_asr','lid','context'].includes(m.id)).every(m=>m.ready);

  return <div className="shell">
    <aside className="sidebar">
      <a className="brand" href="/" aria-label="Subtitle Studio home"><span className="brand-icon"><Subtitles size={25}/></span><span>Subtitle<span className="brand-light">Studio</span></span></a>
      <div className="nav-label">YOUR STUDIO</div>
      <button className={`nav-item ${!modal?'selected':''}`} onClick={()=>setModal(false)}><Layers3 size={18}/>Workspace</button>
      <button className={`nav-item ${modal?'selected':''}`} onClick={()=>setModal(true)}><Settings2 size={18}/>Models & settings</button>
      <div className="nav-label recent-label">RECENT PROJECTS <span>{projects.length}</span></div>
      <div className="recent-list">{projects.slice(0,10).map(p=><button key={p.id} className={`project-link ${project?.id===p.id?'active':''}`} onClick={()=>selectProject(p).catch(fail)}><FileVideo size={16}/><span>{p.media.name}<small>{duration(p.media.duration)} · {p.cue_counts.reduce((n,c)=>n+c.count,0)} cues</small></span></button>)}{!projects.length && <p className="sidebar-hint">Your videos will appear here.<br/>Pick one to get started.</p>}</div>
      <div className="privacy"><ShieldCheck size={18}/><div>Private by design<small>Video and audio stay local.</small></div></div>
      <div className="machine"><span className="status-dot"/><span>{system?.gpu ? system.gpu.name.replace('NVIDIA GeForce ','') : 'Checking GPU…'}<small>{system?.gpu ? `${(system.gpu.free_mb/1024).toFixed(1)} GB available` : 'Local processing'}</small></span><span className="version">v{system?.version || '0.1'}</span></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="breadcrumb">Workspace {project && <><span>/</span><strong>{project.media.name}</strong></>}</div><button className="button quiet small" onClick={()=>setModal(true)}><span className={`status-dot ${ready?'':'amber'}`}/>{ready ? 'Models ready' : 'Set up models'}<Settings2 size={15}/></button></header>
      <div className="content">
        <div className="page-heading"><div><div className="eyebrow">WORDS, WITH CARE</div><h1>{project ? (step==='review' ? 'Fine-tune every word.' : 'From video to subtitles.') : 'Make every word count.'}</h1><p>{project ? 'Faithful transcription, thoughtful review, and subtitles ready to play.' : 'Accurate multilingual subtitles. Entirely on your computer.'}</p></div>{project && <button className="button secondary" onClick={()=>{setProject(undefined);setJob(undefined);setStep('choose');}}><FolderOpen size={17}/>Choose another video</button>}</div>
        <div className="steps">{[['choose','Choose your video'],['process','Transcribe & check'],['review','Review & export']].map(([value,label],i)=><React.Fragment key={value}><button className={`step ${step===value?'current':''}`} disabled={value!=='choose' && !project} onClick={()=>setStep(value as typeof step)}><span>{i+1}</span>{label}</button>{i<2 && <div className="step-line"/>}</React.Fragment>)}</div>
        {error && <div className="alert error" role="alert"><TriangleAlert size={18}/><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
        {notice && <div className="alert success" role="status"><CircleCheck size={18}/>{notice}</div>}
        {!project ? <>
          <section className="upload-card"><div className="file-illustration"><Film size={42} strokeWidth={1.3}/><span className="mini-caption">Aa</span></div><h2>A video. A thousand details.</h2><p>Choose a file and we’ll find its audio tracks and languages.<br/>You decide what to transcribe.</p><button className="button primary large" disabled={opening} onClick={browse}>{opening?<LoaderCircle className="spin" size={19}/>:<FolderOpen size={19}/>}Choose a video<ArrowRight size={17}/></button><div className="format-note">MP4 · MKV · MOV · WEBM · audio files</div><div className="path-row"><input aria-label="Video file path" placeholder="Or paste a file path…" value={path} onChange={e=>setPath(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&path)openVideo(path);}}/><button className="button quiet" disabled={!path||opening} onClick={()=>openVideo(path)}>Open</button></div></section>
          {library.length>0 && <section className="nearby"><div className="section-heading"><h3>Videos in your workspace</h3><span>{library.length} files</span></div><div className="video-grid">{library.map(v=><button key={v.path} className="video-card" disabled={opening} onClick={()=>openVideo(v.path)}><div className="video-icon"><FileVideo size={25}/></div><div><strong>{v.name}</strong><small>{size(v.size)} · Ready to inspect</small></div><ArrowRight size={17}/></button>)}</div></section>}
          <div className="features"><div><Globe2 size={21}/><h3>Across languages</h3><p>Detect languages and changes in conversation.</p></div><div><MessageSquare size={21}/><h3>A second look</h3><p>Two reviewers compare unclear recognition.</p></div><div><Subtitles size={21}/><h3>Ready to watch</h3><p>Export an SRT or open your video in VLC.</p></div></div>
        </> : <>
          {step==='choose' && <><section className="media-summary"><div className="video-icon"><Film size={28}/></div><div><h2>{project.media.name}</h2><p>{duration(project.media.duration)} · {size(project.media.size)} · {project.media.audio_tracks.length} audio {project.media.audio_tracks.length===1?'track':'tracks'}</p></div><span className="pill"><ShieldCheck size={13}/>Local file</span></section>
            {project.media.warnings.length>0 && <div className="alert warning"><TriangleAlert size={17}/><span>This container has metadata warnings. The original file is preserved; decoding will be checked during processing.</span></div>}
            <div className="configure-grid"><section className="panel"><div className="section-heading"><div><h3>Select audio tracks</h3><p>Each selected track gets its own subtitles.</p></div><button className="button quiet small" disabled={busy(job)} onClick={()=>api<Job>(`/projects/${project.id}/scan`,'POST',{}).then(setJob).catch(fail)}><RefreshCw size={15}/>Scan languages</button></div>
              {project.media.audio_tracks.map(t=><label className={`track-card ${tracks.includes(t.stream_index)?'checked':''}`} key={t.stream_index}><input type="checkbox" checked={tracks.includes(t.stream_index)} onChange={()=>setTracks(tracks.includes(t.stream_index)?tracks.filter(x=>x!==t.stream_index):[...tracks,t.stream_index])}/><AudioLines size={22}/><div><strong>{t.title || `Audio ${t.audio_ordinal+1}`}</strong><small>{t.channels} channels · {t.codec?.toUpperCase()}</small></div><div className="track-languages">{t.languages.length ? t.languages.map(l=><span className="pill" key={l.code}>{lang(l.code)}</span>) : <small>{busy(job)&&job?.kind==='scan'?'Detecting…':t.detection==='no_speech_in_samples'?'No speech in samples':'Not yet detected'}</small>}<small>{t.detection==='full_track'?'Full-track scan':t.detection==='processed_range'?'Processed range':t.detection==='sampled'?'Sampled estimate':''}</small></div></label>)}
              {!project.media.audio_tracks.length && <div className="empty"><AudioLines/><p>This file has no audio track.</p></div>}{busy(job)&&job?.kind==='scan' && <div className="inline-progress"><LoaderCircle className="spin" size={16}/>{job.message}<span>{Math.round(job.progress*100)}%</span></div>}
              <div className="info-note">Language changes are checked throughout the selected audio during transcription.</div>
            </section><section className="panel"><h3>Recognition preferences</h3><label className="field">Source language<select value={sourceLanguage} onChange={e=>setSourceLanguage(e.target.value)}><option value="">Detect automatically</option>{languages.transcription.map(code=><option value={code} key={code}>{lang(code)}</option>)}</select></label><div className="preset-selector"><button className={preset==='accurate'?'active':''} onClick={()=>setPreset('accurate')}><Sparkles size={17}/><strong>Accurate</strong><small>Whisper large-v3</small></button><button className={preset==='fast'?'active':''} onClick={()=>setPreset('fast')}><AudioLines size={17}/><strong>Faster</strong><small>Whisper turbo</small></button></div>
              <label className="toggle"><input type="checkbox" checked={recheck} onChange={e=>{setRecheck(e.target.checked);if(!e.target.checked)setDebate(false);}}/><div><strong>Recheck uncertain speech</strong><small>An additional recognizer checks difficult passages.</small></div></label><label className="toggle"><input type="checkbox" disabled={!recheck} checked={debate} onChange={e=>setDebate(e.target.checked)}/><div><strong>Two-agent context review</strong><small>Compare recognition candidates using nearby dialogue.</small></div></label>
              <details><summary>Try a short section first</summary><label className="toggle"><input type="checkbox" checked={sample} onChange={e=>setSample(e.target.checked)}/><span>Process a 2-minute sample</span></label>{sample && <label className="field">Start at (seconds)<input type="number" min="0" value={sampleStart} onChange={e=>setSampleStart(Number(e.target.value))}/></label>}</details>
            </section></div><div className="start-row"><p><ShieldCheck size={16}/>Original video and spoken wording stay intact.</p><button className="button primary large" disabled={!tracks.length||busy(job)} onClick={start}>Create subtitles<ArrowRight size={18}/></button></div></>}
          {step==='process' && <section className="process-card"><div className="process-symbol">{job?.status==='done'?<CircleCheck size={42}/>:<AudioLines size={42}/>}</div><div className="eyebrow">{job?.stage.replaceAll('_',' ') || 'READY TO START'}</div><h2>{busy(job)?'Listening closely.':job?.status==='done'?'Your subtitles are ready.':job?.status==='failed'?'Let’s resolve this.':'Progress saved.'}</h2><p>{job?.message || 'Choose the tracks and start transcription.'}</p><div className="progress-track"><div style={{width:`${(job?.progress||0)*100}%`}}/></div><div className="progress-details"><span>{Math.round((job?.progress||0)*100)}%</span><span>{job?.elapsed ? `${duration(job.elapsed)} elapsed` : 'Preparing'}{job && job.progress>.05 && busy(job) ? ` · ~${duration(job.elapsed*(1/job.progress-1))} remaining` : ''}</span></div><div className="stage-list">{['Transcribe','Recheck','Discuss','Align'].map((name,i)=><span key={name} className={(job?.progress||0)>[0,.65,.83,.96][i]?'reached':''}><CircleCheck size={16}/>{name}</span>)}</div>{job?.error && <div className="alert error"><TriangleAlert size={17}/><span>{job.error}</span></div>}{job?.warnings.map(w=><div className="alert warning" key={w}>{w}</div>)}<div className="process-actions">{busy(job)?<button className="button secondary" onClick={()=>api<Job>(`/jobs/${job?.id}/pause`,'POST',{}).then(setJob).catch(fail)}><Pause size={17}/>Pause & save</button>:job&&job.status!=='done'?<button className="button primary" onClick={()=>api<Job>(`/jobs/${job.id}/resume`,'POST',{}).then(setJob).catch(fail)}><Play size={17}/>Resume</button>:null}<button className="button primary" onClick={()=>setStep('review')}><Subtitles size={17}/>Open transcript</button></div><small>Unclear passages stay flagged for your review, even when the agents agree.</small></section>}
          {step==='review' && selectedTrack && <Review project={project} track={selectedTrack} tracks={tracks} languages={languages.translation} job={job} onJob={setJob} fail={fail} notify={notify} onTrack={t=>setTracks([t])}/>}
        </>}
        <footer><span>Subtitle Studio</span><span>Built for the words that were actually spoken.</span></footer>
      </div>
    </main>
    {modal && system && <SettingsModal system={system} close={()=>setModal(false)} reload={reloadSystem} fail={fail} notify={notify}/>}
  </div>;
}

function Review({project,track,languages,job,onJob,fail,notify,onTrack}: {project:Project;track:Track;tracks:number[];languages:string[];job?:Job;onJob:(j:Job)=>void;fail:(e:unknown)=>void;notify:(s:string)=>void;onTrack:(t:number)=>void}) {
  const [cues,setCues] = useState<Cue[]>([]), [selected,setSelected] = useState<string>(''), [filter,setFilter] = useState(false), [search,setSearch] = useState(''), [target,setTarget] = useState('fa'), [translated,setTranslated] = useState(false), [draft,setDraft] = useState(''), [clip,setClip] = useState<Clip>(), [loadingClip,setLoadingClip] = useState(false);
  const listRef = useRef<HTMLDivElement>(null), video = useRef<HTMLVideoElement>(null);
  const cue = cues.find(c=>c.id===selected);
  const visible = cues.filter(c=>(!filter || (c.flags.length&&!c.reviewed)) && (!search || c.text.toLocaleLowerCase().includes(search.toLocaleLowerCase())));
  const virtual = useVirtualizer({count:visible.length,getScrollElement:()=>listRef.current,estimateSize:()=>88,overscan:8});
  async function reload(){const items=await api<Cue[]>(`/projects/${project.id}/cues?track=${track.stream_index}${translated?'&language='+target:''}`);setCues(items);setSelected(old=>items.some(c=>c.id===old)?old:items[0]?.id || '');}
  useEffect(()=>{reload().catch(fail);},[project.id,track.stream_index,job?.status,translated,target]);
  useEffect(()=>{setDraft(cue?.text || '');},[cue?.id,cue?.text]);
  useEffect(()=>{if(!cue)return;let cancelled=false;setLoadingClip(true);const timer=window.setTimeout(()=>api<Clip>(`/projects/${project.id}/preview`,'POST',{track:track.stream_index,start:Math.max(0,cue.start-2),duration:Math.min(25,cue.end-cue.start+4)}).then(result=>{if(!cancelled)setClip(result);}).catch(e=>{if(!cancelled)fail(e);}).finally(()=>{if(!cancelled)setLoadingClip(false);}),250);return()=>{cancelled=true;clearTimeout(timer);};},[cue?.id,cue?.start,cue?.end,track.stream_index]);
  useEffect(()=>{function key(e:KeyboardEvent){if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName))return;if(e.code==='Space'){e.preventDefault();if(video.current){video.current.paused?video.current.play().catch(()=>{}):video.current.pause();}}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const at=visible.findIndex(c=>c.id===selected);const next=Math.max(0,Math.min(visible.length-1,at+(e.key==='ArrowDown'?1:-1)));setSelected(visible[next]?.id || '');virtual.scrollToIndex(next);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[selected,visible]);
  async function edit(changes: Partial<Cue>){if(!cue)return;const updated=await api<Cue>(`/projects/${project.id}/cues/${cue.id}`,'PATCH',changes);setCues(old=>old.map(c=>c.id===updated.id?updated:c));}
  async function exporting(){const result=await api<{path:string}>(`/projects/${project.id}/export`,'POST',{track:track.stream_index,language:translated?target:'original'});notify(`Saved: ${result.path}`);}
  const flagged = cues.filter(c=>c.flags.length&&!c.reviewed).length;
  return <><div className="review-toolbar"><div><strong>{cues.length} subtitle cues</strong><span>{flagged ? `${flagged} need a closer look`:'Ready for your review'}</span></div><div className="toolbar-actions"><select aria-label="Review audio track" value={track.stream_index} onChange={e=>onTrack(Number(e.target.value))}>{project.media.audio_tracks.map(t=><option value={t.stream_index} key={t.stream_index}>{t.title||`Audio ${t.audio_ordinal+1}`}</option>)}</select><button className="button secondary" disabled={!cues.length} onClick={()=>exporting().catch(fail)}><Download size={16}/>Export SRT</button><button className="button primary" disabled={!cues.length} onClick={()=>api(`/projects/${project.id}/play`,'POST',{track:track.stream_index,language:translated?target:'original'}).then(()=>notify('Opened in VLC with the selected audio and subtitles.')).catch(fail)}><Play size={16}/>Play in VLC</button></div></div>
    <div className="review-grid"><section className="transcript-panel"><div className="transcript-controls"><input aria-label="Search transcript" placeholder="Search spoken words…" value={search} onChange={e=>setSearch(e.target.value)}/><button className={`button small ${filter?'active-filter':'quiet'}`} onClick={()=>setFilter(!filter)}><TriangleAlert size={14}/>Needs review {flagged>0&&<span>{flagged}</span>}</button></div><div className="cue-list" ref={listRef}>{!visible.length?<div className="empty"><Subtitles size={28}/><h3>{cues.length?'No matching cues':'No subtitles yet'}</h3><p>{cues.length?'Try another search or filter.':'Start transcription to see the spoken words here.'}</p></div>:<div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map(row=>{const c=visible[row.index];return <button className={`cue-row ${c.id===selected?'selected':''}`} key={c.id} style={{position:'absolute',top:0,left:0,width:'100%',height:row.size,transform:`translateY(${row.start}px)`}} onClick={()=>setSelected(c.id)}><div className="cue-time"><span>{duration(c.start)}</span><small>{row.index+1}</small></div><div className="cue-words" dir="auto">{translated ? c.translated_text || 'Translation not available yet' : c.text}<small dir="ltr">{translated ? `${lang(target)} · from ${lang(c.language)}` : lang(c.language)}{c.reviewed?' · Reviewed':c.flags.length?' · Needs review':''}</small></div>{c.reviewed?<Check size={15} className="green"/>:c.flags.length?<span className="review-dot"/>:null}</button>;})}</div>}</div><div className="transcript-footer">↑ ↓ Move between cues <span>Space Play / pause</span></div></section>
      <aside className="inspector"><div className="preview-player">{clip?<video ref={video} src={clip.url} controls preload="metadata" playsInline/>:<div className="preview-empty"><Film size={35}/><p>Select a cue to preview</p></div>}{loadingClip&&<div className="preview-loading"><LoaderCircle className="spin" size={19}/>Preparing selected audio…</div>}</div>{clip && <div className="waveform" onClick={e=>{if(video.current){const rect=e.currentTarget.getBoundingClientRect();video.current.currentTime=(e.clientX-rect.left)/rect.width*clip.duration;}}} role="img" aria-label="Audio waveform">{clip.peaks.map((peak,i)=><span key={i} style={{height:Math.max(3,Math.min(34,peak*90))}}/>)}</div>}
      {cue && <div className="cue-inspector"><div className="section-heading"><h3>Spoken words</h3><span className="pill">{lang(cue.language)}</span></div><textarea dir="auto" aria-label="Edit spoken words" value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==cue.text)edit({text:draft}).catch(fail);}}/><div className="timings"><label>Start (seconds)<input aria-label="Cue start" key={cue.id+'start'} type="number" step="0.01" min="0" defaultValue={cue.start.toFixed(2)} onBlur={e=>edit({start:Number(e.target.value)}).catch(fail)}/></label><label>End (seconds)<input aria-label="Cue end" key={cue.id+'end'} type="number" step="0.01" min="0" defaultValue={cue.end.toFixed(2)} onBlur={e=>edit({end:Number(e.target.value)}).catch(fail)}/></label></div><button className={`button full ${cue.reviewed?'secondary':'primary'}`} onClick={()=>edit({reviewed:!cue.reviewed}).catch(fail)}><Check size={16}/>{cue.reviewed?'Reviewed · undo':'Mark reviewed'}</button>
      {cue.flags.length>0 && <div className="review-explanation"><strong><TriangleAlert size={15}/>Why this needs review</strong><p>{cue.flags.join(' · ')}</p>{cue.verification && <small>{cue.verification}</small>}</div>}
      {cue.candidates.length>1 && <details className="candidate-details" open><summary><MessageSquare size={16}/>Recognition & context review</summary><p className="muted">{cue.decision?.status==='agreed'?'Both reviewers selected the same candidate. The passage remains uncertain until you review it.':cue.decision?.status==='unresolved'?'Reviewers disagreed; the original best guess was kept.':'Compare the available recognition candidates.'}</p>{cue.candidates.map(candidate=><button key={candidate.id} className={`candidate ${candidate.text===cue.text?'chosen':''}`} onClick={()=>api<Cue>(`/projects/${project.id}/cues/${cue.id}/candidate`,'POST',{candidate_id:candidate.id}).then(updated=>setCues(old=>old.map(c=>c.id===updated.id?updated:c))).catch(fail)}><strong>{candidate.engine}{candidate.text===cue.text&&<Check size={13}/>}</strong><span dir="auto">{candidate.text}</span></button>)}{cue.decision?.votes.map((vote,i)=><div className="agent-note" key={i}><strong>{vote.role==='recognition'?'Recognition reviewer':'Context reviewer'} · round {vote.round}</strong><p>{vote.reason}</p></div>)}</details>}
      </div>}<div className="translation-box"><h3><Globe2 size={17}/>Optional translation</h3><p>The original words remain separate.</p><div className="translation-row"><select aria-label="Translation language" value={target} onChange={e=>setTarget(e.target.value)}>{languages.map(code=><option value={code} key={code}>{lang(code)}</option>)}</select><button className="button secondary" disabled={!cues.length||busy(job)} onClick={()=>api<Job>(`/projects/${project.id}/translate`,'POST',{tracks:[track.stream_index],target_language:target}).then(onJob).catch(fail)}>Translate</button></div><label className="toggle"><input type="checkbox" checked={translated} onChange={e=>setTranslated(e.target.checked)}/><span>Show translated subtitles</span></label>{job?.kind==='translate' && <><small>{job.status==='done' ? 'Translation ready.' : `${job.message} · ${Math.round(job.progress*100)}%`}</small>{job.error && <div className="alert error" role="alert">{job.error}</div>}{job.warnings.map(w=><div className="alert warning" key={w}>{w}</div>)}{busy(job) ? <button className="button quiet small" onClick={()=>api<Job>(`/jobs/${job.id}/pause`,'POST',{}).then(onJob).catch(fail)}><Pause size={14}/>Pause translation</button> : ['paused','failed','cancelled'].includes(job.status) ? <button className="button secondary small" onClick={()=>api<Job>(`/jobs/${job.id}/resume`,'POST',{}).then(onJob).catch(fail)}><Play size={14}/>Resume translation</button> : null}</>}</div></aside>
    </div></>;
}

function SettingsModal({system,close,reload,fail,notify}:{system:System;close:()=>void;reload:()=>Promise<void>;fail:(e:unknown)=>void;notify:(s:string)=>void}){
  const [modelsRoot,setModelsRoot]=useState(system.models_root),[ollamaRoot,setOllamaRoot]=useState(system.ollama_models),[tools,setTools]=useState(system.tools),[setup,setSetup]=useState<Job|undefined>(system.setup_jobs.find(busy));
  useEffect(()=>{if(!setup||!busy(setup))return;const source=new EventSource(`/api/jobs/${setup.id}/events?k=${encodeURIComponent(window.STUDIO_TOKEN)}`);source.onmessage=e=>{const j=JSON.parse(e.data);setSetup(j);if(!busy(j)){source.close();reload().catch(fail);}};return()=>source.close();},[setup?.id,setup?.status]);
  async function install(keys:string[]){try{setSetup(await api<Job>('/models/install','POST',{models:keys}));}catch(e){fail(e);}}
  async function restart(){try{await api('/restart','POST',{});notify('Restarting Subtitle Studio…');for(let n=0;n<40;n++){await new Promise(resolve=>setTimeout(resolve,500));try{const response=await fetch('/health');if(n>2&&response.ok){window.location.reload();return;}}catch{}}throw new Error('Use Start.bat to reopen Subtitle Studio.');}catch(e){fail(e);}}
  return <div className="modal-backdrop"><section className="settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div className="modal-heading"><div><div className="eyebrow">YOUR LOCAL SETUP</div><h2 id="settings-title">Models & settings</h2></div><button className="icon-button" aria-label="Close settings" onClick={close}><X/></button></div><p className="muted">Models are downloaded once. Compatible existing models are reused.</p><div className="model-list">{system.models.map(model=><div className="model-row" key={model.id}><div className={`model-symbol ${model.ready?'installed':''}`}>{model.ready?<Check size={18}/>:<Download size={18}/>}</div><div><strong>{model.name}</strong><small>{model.id==='translation'?'Optional translation':model.id==='turbo'?'Optional faster recognition':model.id==='context'?'Two reviewers, one shared model':'Accurate recognition'} · ~{model.size_gb} GB</small></div>{model.ready?<span className="pill green">Installed</span>:<button className="button secondary small" disabled={busy(setup)} onClick={()=>install([model.id])}>Download</button>}</div>)}</div><button className="button primary full" disabled={busy(setup)||system.models.filter(m=>['whisper','qwen_asr','lid','context'].includes(m.id)).every(m=>m.ready)} onClick={()=>install(system.models.filter(m=>['whisper','qwen_asr','lid','context'].includes(m.id)&&!m.ready).map(m=>m.id))}><Download size={17}/>Install accurate-mode models</button>{setup&&<div className="setup-progress"><p>{setup.message}</p><div className="progress-track"><div style={{width:`${setup.progress*100}%`}}/></div>{setup.error&&<div className="alert error">{setup.error}</div>}</div>}<div className="settings-folders"><h3>Storage locations</h3><label className="field">Recognition model folder<input value={modelsRoot} onChange={e=>setModelsRoot(e.target.value)}/></label><label className="field">Ollama model folder<input value={ollamaRoot} onChange={e=>setOllamaRoot(e.target.value)}/></label><p className="muted">Use any drive. Location preferences stay on this computer and are excluded from Git.</p><details><summary>Tool executables</summary>{Object.entries(tools).map(([name,value])=><label key={name} className="field">{name}<input value={value||''} placeholder="Automatically detect" onChange={e=>setTools({...tools,[name]:e.target.value||null})}/></label>)}</details><button className="button secondary" onClick={()=>api<{message:string}>('/settings','POST',{models_root:modelsRoot,ollama_models:ollamaRoot,tools}).then(result=>notify('Locations saved. Use Restart app to apply them.')).catch(fail)}>Save locations</button><button className="button quiet" onClick={restart}><RefreshCw size={15}/>Restart app</button></div></section></div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
